# Generated by Django 5.2.11 on 2026-02-19 22:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('each', 'Each'), ('dozen', 'Dozen'), ('kg', 'Kilogram'), ('g', 'Grams'), ('lb', 'Pound'), ('bunch', 'Bunch'), ('bag', 'Bag'), ('box', 'Box'), ('litre', 'Litre')], max_length=10)),
                ('availability', models.CharField(choices=[('in_season', 'In Season'), ('out_of_season', 'Out of Season'), ('pre_order', 'Pre-Order')], default='in_season', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('best_before', models.DateField(blank=True, null=True)),
                ('origin_location', models.CharField(max_length=100)),
                ('is_organic', models.BooleanField(null=True)),
                ('storage_instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='products', to='products.allergen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
