# Generated by Django 5.2.12 on 2026-03-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allergen_product'),
        ('products', '0003_product_producer'),
    ]

    operations = [
    ]
